Traceback (most recent call last):
  File "print_test.py", line 4, in <module>
    assert 0==1
AssertionError
